spring.application.name=CadastroDeNinjas

# Define a URL do banco (criando um banco em memória chamado 'testdb')
# Quando fechar o banco de dados, eles vão ficar persistidos em memoria até as tabelas serem deletadas.
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Diz ao Hibernate para criar/atualizar as tabelas no banco automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Habilita o painel de administração web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console